nolebase/integrations

.github/workflows/ci.yaml, .github/workflows/preview-docs-deployment.yaml, docs/vite.config.ts, packages/markdown-it-bi-directional-links/src/index.ts, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/vite/index.ts
Try to fix for https://github.com/nolebase/nolebase/issues/28
=> fix: make plugins compatible for Windows

docs/vite.config.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/markdownSection.ts, packages/vitepress-plugin-page-properties/src/vite/index.ts
=> fix: unspecified plugin ordering caused incorrect markdown transformation after rendering

docs/.vitepress/theme/index.ts, docs/package.json, packages/unconfig-vitepress/README.md, packages/unconfig-vitepress/build.config.ts, packages/unconfig-vitepress/package.json, packages/unconfig-vitepress/src/index.ts, packages/unconfig-vitepress/src/theme.ts, packages/unconfig-vitepress/tsconfig.json, packages/vitepress-plugin-highlight-targeted-heading/tsconfig.json, packages/vitepress-plugin-highlight-targeted-heading/tsconfig.node.json, packages/vitepress-plugin-inline-link-preview/tsconfig.json, packages/vitepress-plugin-inline-link-preview/tsconfig.node.json, packages/vitepress-plugin-page-properties/src/client/index.ts, packages/vitepress-plugin-page-properties/tsconfig.node.json, pnpm-lock.yaml, tsconfig.json
=> refactor(config): added unconfig-vitepress

packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/vite/git.ts, pnpm-lock.yaml
=> refactor(git-changelog): fetch and calculate git logs concurrently and improved the user experiences

.vscode/settings.json, docs/.vitepress/theme/index.ts, packages/unconfig-vitepress/src/plugins/nolebase/index.ts, packages/unconfig-vitepress/src/theme.ts, packages/unconfig-vitepress/src/types.ts
=> refactor(unconfig-vitepress): supported plugins and plugin sets, implemented NolebasePluginSet

.vscode/settings.json, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/utils.ts, packages/vitepress-plugin-git-changelog/src/client/virtual.d.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, pnpm-lock.yaml
=> fix(git-changelog): replaced deprecated md5 with uncrypto and fix the export issue

.gitignore, docs/.vitepress/theme/index.ts, packages/ui/package.json, packages/ui/src/components/NuLazyDOMRiveCanvas.vue, packages/ui/src/index.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts
=> fix(ui): broken @rive dependencies

packages/markdown-it-bi-directional-links/src/index.ts
In rare scenarioes, extname may parse version numbers from titles, such as:
1. `[[How to install Kubernetes 1.28]]`, where `.28` would be parsed as extname;
2. `[[Changelog for Vite 5.5.0 - Know the new upcomings]]`, where `.0 - Know the new upcomings` would be parsed as extname
=> fix(bi-directional-links): forced to suffix `.md` extname to match

docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-vite-plugins.md, docs/pages/en/integrations/vitepress-plugin-git-changelog/getting-started.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-vite-plugins.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/getting-started.md, packages/vitepress-plugin-git-changelog/build.config.ts, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/vite/git.test.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts, pnpm-lock.yaml
=> feat(git-changelog): added rewritePathsBy.handler support to dynamically transform paths

packages/vitepress-plugin-enhanced-mark/package.json, packages/vitepress-plugin-enhanced-readabilities/package.json, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-highlight-targeted-heading/package.json, packages/vitepress-plugin-inline-link-preview/package.json, packages/vitepress-plugin-page-properties/package.json, packages/vitepress-plugin-thumbnail-hash/package.json, pnpm-lock.yaml
=> fix(enhanced-readabilities): bad dependency for @nolebase/ui

.vscode/extensions.json, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitTagLine.vue, packages/vitepress-plugin-git-changelog/src/client/composables/commits.ts, packages/vitepress-plugin-git-changelog/src/client/virtual.d.ts, packages/vitepress-plugin-git-changelog/src/types/index.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
=> fix(git-changelog): bad tag parsing

docs/pages/en/integrations/vitepress-plugin-git-changelog/getting-started.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/getting-started.md
=> docs: fixed a typo in git-changelog, styles.css -> style.css

docs/.vitepress/config.ts, docs/public/_redirects
Integrated privacy-friendly, developers first, GDPR compliant analytics platform with [plausible.io](https://plausible.io).
Proxying Plausible through Netlify | Plausible docs
https://plausible.io/docs/proxy/guides/netlify
=> feat: integrated plausible.io

packages/vitepress-plugin-git-changelog/src/vite/git.ts
=> fix(git-changelog): join srcDir with filePath sent from hmr

cspell.config.yaml, docs/.vitepress/theme/index.ts, docs/pages/en/integrations/vitepress-plugin-enhanced-mark/index.md, docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/en/releases/migrations/v1-to-v2.md, docs/pages/zh-CN/integrations/vitepress-plugin-enhanced-mark/index.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/releases/migrations/v1-to-v2.md, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/composables/author.test.ts, packages/vitepress-plugin-git-changelog/src/client/composables/author.ts, packages/vitepress-plugin-git-changelog/src/client/index.ts, packages/vitepress-plugin-git-changelog/src/client/types.ts, packages/vitepress-plugin-git-changelog/src/types/index.ts
=> refactor: simplify `mapContributors` configuration

docs/.vitepress/theme/index.ts, packages/vitepress-plugin-git-changelog/src/client/composables/author.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
=> fix(git-changelog): missing trim for fields

docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/constants.ts, packages/vitepress-plugin-git-changelog/src/client/types.ts, packages/vitepress-plugin-git-changelog/src/types/index.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts, pnpm-lock.yaml
=> refactor(git-changelog): migrate commitHashDigits option to UI section as numCommitHashLetters

packages/ui/src/components/NuAsciinemaPlayer.vue, packages/ui/src/components/NuLazyTeleportRiveCanvas.vue, packages/ui/src/components/deps.ts, packages/vitepress-plugin-enhanced-readabilities/src/client/components/Menu.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/deps.ts, packages/vitepress-plugin-git-changelog/build.config.ts, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitTagLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/types.ts
https://github.com/vue-macros/vue-macros/actions/runs/9340953898/job/25707140019?pr=695
=> fix: type error with users' vue-tsc

docs/pages/en/integrations/vitepress-plugin-enhanced-readabilities/index.md, docs/pages/zh-CN/integrations/vitepress-plugin-enhanced-readabilities/index.md, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitch.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchContentLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchPageLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/types.ts
feat(enhanced-readabilities): option to disable animation
Close #233
=> feat(enhanced-readabilities): option to disable animation

packages/vitepress-plugin-inline-link-preview/src/markdown-it/index.test.ts, packages/vitepress-plugin-inline-link-preview/src/markdown-it/index.ts
=> fix(inline-link-preview): bad handling implementation of tag replacing without the check of nested seek

packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/types.ts
=> feat(git-changelog): add option to hide header

docs/.vitepress/theme/index.ts, docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/unconfig-vitepress/src/plugins/nolebase/index.ts, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitTagLine.vue, packages/vitepress-plugin-git-changelog/src/client/composables/commits.ts, packages/vitepress-plugin-git-changelog/src/client/types.ts, packages/vitepress-plugin-git-changelog/src/client/utils.ts
=> feat(git-changelog): new options for displaying commits in relative distance from now

docs/.vitepress/theme/index.ts, docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/types.ts
=> docs(git-changelog): updated docs and aligned feature implementation for git-changelog components

docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/types.ts
=> feat(git-changelog): new option to hide sort by

packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/composables/changelog.ts, packages/vitepress-plugin-git-changelog/src/client/types.ts, packages/vitepress-plugin-git-changelog/src/types/index.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
Close https://github.com/nolebase/integrations/issues/258
=> feat(git-changelog): display commit authors inside line with avatars

packages/vitepress-plugin-og-image/package.json, packages/vitepress-plugin-og-image/src/vitepress/constants.ts, packages/vitepress-plugin-og-image/src/vitepress/index.ts, packages/vitepress-plugin-og-image/src/vitepress/options.test.ts, packages/vitepress-plugin-og-image/src/vitepress/options.ts, packages/vitepress-plugin-og-image/src/vitepress/types.ts, pnpm-lock.yaml
=> feat(og-image): new option to disable existing meta tag overriding, completed some of the ut

packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitch.vue
=> fix(enhanced-readabilities): do not add animation when specified on mounted

.github/renovate.json
=> chore(renovate): fix renovate config error

docs/pages/zh-CN/integrations/vitepress-plugin-breadcrumbs/index.md
=> docs(breadcrumbs): fix typo

.devcontainer/devcontainer.json
=> chore: add github codespace config

.github/renovate.json
https://docs.renovatebot.com/configuration-options/#rangestrategy
=> chore(renovate): bump version range in package.json

packages/vitepress-plugin-sidebar/src/sidebar.ts
=> fix(sidebar): type constrainted to `true`

packages/vitepress-plugin-enhanced-readabilities/src/client/components/SpotlightHoverBlock.vue
=> fix(enhance-readabilities): remove invalid border solid issue

pnpm-lock.yaml, pnpm-workspace.yaml
https://github.com/nolebase/integrations/pull/387#discussion_r1943322213
=> fix: vitepress version specifier

docs/uno.config.ts, packages/markdown-it-unlazy-img/src/index.ts
=> fix(unlazy-img): extra pattern for glob to search
