nolebase/integrations

packages/vitepress-plugin-enhanced-readabilities/src/components/MenuHelp.vue
修复 https://github.com/nolebase/integrations/issues/47
=> 修复：提示框在元素不可见的情况依然可以被触发的BUG

docs/.vitepress/theme/components/RiveCanvas.vue, docs/.vitepress/theme/index.ts, docs/.vitepress/theme/styles/vars.css, docs/package.json, docs/vite.config.ts, packages/ui/package.json, packages/ui/src/index.ts, packages/vitepress-plugin-git-changelog/src/vite/markdownSection.ts, packages/vitepress-plugin-page-properties/src/vite/markdownSection.ts, pnpm-lock.yaml
Follow up #124 and #127 .
Temporarily removed `RiveCanvas` components for #91 that required by #94 out back to `integrations-docs` package as direct imported dependencies while waiting for feedbacks and confirmation of fixes by developers of @rive-app.
=> fix(ui): broken @rive-app/canvas dependencies when import outside from bundled packages

.vscode/settings.json, docs/.vitepress/theme/index.ts, packages/ui/README.md, packages/ui/build.config.ts, packages/ui/package.json, packages/ui/src/components/NuLazyTeleportRiveCanvas.vue, packages/ui/src/index.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, pnpm-lock.yaml
When I was working on #124, I found out that the `@rive-app/canvas` break the other components then came up the temporarily fix at #128. However, the issue didn't went off, after fixing issues with `fast-glob`, I noticed that the CJS / UMD limitations for `@rive-app/canvas` where I may have a solution to fix.
According to `@rive-app/canvas`'s [documentation](https://help.rive.app/runtimes/overview/web-js#id-1.-install-the-dependency), developers should use the package like this:
```js
import * as rive from '@rive-app/canvas'
```
However, the error will appear as follow or either as what users had described in #124:
```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'rive')
at webpackUniversalModuleDefinition (universalModuleDefinition:9:1)
at …
```
=> fix(ui|git-changelog): missing configurations for @rive-app/canvas

packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
=> feat(git-changelog): include extensions option

docs/package.json, docs/pages/en/ui/asciinema-player/index.md, docs/pages/en/ui/lazy-teleport-rive-canvas/index.md, docs/pages/zh-CN/ui/asciinema-player/index.md, docs/pages/zh-CN/ui/lazy-teleport-rive-canvas/index.md, docs/vite.config.ts, packages/ui/build.config.ts, packages/ui/package.json, packages/vitepress-plugin-enhanced-readabilities/package.json, packages/vitepress-plugin-enhanced-readabilities/src/client/index.ts, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-git-changelog/src/client/index.ts, packages/vitepress-plugin-highlight-targeted-heading/package.json, packages/vitepress-plugin-inline-link-preview/package.json, packages/vitepress-plugin-inline-link-preview/src/client/index.ts, packages/vitepress-plugin-og-image/package.json, packages/vitepress-plugin-page-properties/package.json, packages/vitepress-plugin-page-properties/src/client/index.ts, packages/vitepress-plugin-thumbnail-hash/package.json, pnpm-lock.yaml
```
Internal server error: 
Failed to resolve import "@nolebase/ui/client/style.css" from "node_modules/.pnpm/@nolebase+vitepress-plugin-git-changelog@2.0.0-rc6_vitepress@1.1.0_vue@3.4.21/node_modules/@nolebase/vitepress-plugin-git-changelog/dist/client/index.mjs?v=90fb9ea1".
Does the file exist?
```
1. Missing `@nolebase/ui/style.css` exports
```json
{
"exports": {
".": {
"types": "./dist/index.d.ts",
"import": "./dist/index.mjs",
"require": "./dist/index.js"
},
"./*": {
"types": "./dist/*",
"import": "./dist/*.mjs",
"require": "./dist/*.js"
}
}
}
```
2. Bad build exports for `@nolebase/ui/client/style.css` in `@nolebase/ui`, should be `@nolebase/ui/style.css`.
3. Bad import for `@nolebase/ui/client/style.css` from all the other packages, should be `@nolebase/ui/style.css`
4. Bad …
=> fix(ui): incorrect style exports

packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue
=> fix(git-changelog): block element should not be warpped in inline element

packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-thumbnail-hash/src/vite/index.ts
涉及插件：git-changelog、ThumbnailHashImages
修复在 build 结束后插件的 spinner 还在转动，build 进程没有退出的问题。ref: https://github.com/nolebase/integrations/issues/191#issuecomment-2095003014
before:
after:
VitePress 在 build 时，为 `building client + server bundles...` 和 `rendering pages...` 分别启动了一个 ora 实例，插件启动的 ora 实例在 `building client + server bundles...` 这一步结束前，相当于 build 时，同时启动了两个 spinner 。
而 ora 尚不支持同时启动两个 spinner ：https://github.com/sindresorhus/ora/issues/116 。
因此我们需要在 build 时禁用插件的 spinner。
其他替代方案：
- 使用其他 spinner 库，例如 https://github.com/listr2/listr2
- 向 VitePress 反馈（大概率行不通）
=> fix: disable spinner in production mode

docs/.vitepress/theme/index.ts, packages/vitepress-plugin-git-changelog/src/client/composables/author.test.ts, packages/vitepress-plugin-git-changelog/src/client/composables/author.ts
=> fix(git-changelog): mapAuthors.name also include in nameAlias, default return github link when no links but with username

packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitch.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchContentLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchPageLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/MenuTitle.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/ScreenLayoutSwitch.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/ScreenMenu.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/ScreenSpotlight.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/Spotlight.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/SpotlightStyles.vue
Fix
```shell
[unocss] failed to load icon "icon-park-outline:icon-book-open"
```
Issue.
But I still think this is related to @unocss. Since we used the attribute `icon="i-icon-park-outline:layout-one"` to specify the icons, may result `unocss` to think `i-icon-park-outline:layout-one` is some sort of the `icon` that needs to be transformed with.
=> fix(enhanced-readabilities): [unocss] failed to load icon

packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue
=> refactor(git-changelog): use a 7-digit commit hash instead of a 5-digit

README.md, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/locales/en.yaml, packages/vitepress-plugin-git-changelog/src/locales/zh-CN.yaml, packages/vitepress-plugin-git-changelog/src/types/index.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts, packages/vitepress-plugin-git-changelog/src/vite/types.ts, packages/vitepress-plugin-graph-view/src/client/components/GraphView.vue
use titleId for heading, support changing commit order and customizing commit hash digits, update README.md
=> feat(git-changelog): use titleId for heading, support changing commit order and customizing commit hash digits

packages/markdown-it-bi-directional-links/src/index.ts
Reason 1: The image path may have space around
Reason2: The attachment should only recognized by extension
The image maybe [[image.png]] instead of ![[image.png]]
=> fix(bi-directional-links): trim src + including non-attachment markup

packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue
=> fix(git-changelog): initial dev commits not handled

packages/vitepress-plugin-og-image/package.json, packages/vitepress-plugin-og-image/src/vitepress/index.ts, packages/vitepress-plugin-og-image/src/vitepress/utils/svg/render.ts, packages/vitepress-plugin-og-image/src/vitepress/utils/vitepress/sidebar.ts, pnpm-lock.yaml
I've made some changes to the `@nolebase/vitepress-plugin-og-image` package to improve its stability and add missing features that I needed in my project.
* Fixed an issue where documents from the sidebar were not resolved like how Vitepress resolves them
* Added support for rendering images inside the SVG template
* Added support for passing custom font buffers
* Added configuration option to specify a custom SVG template path
* Improved the line splitting algorithms to attempt to split by spaces or capital letters (useful for camelCase text)
* Made sure that an `og:image` meta tag is not added if it already exists in the HTML
=> feat(og image): enhanced configuration, image URL support

packages/vitepress-plugin-og-image/src/vitepress/index.ts, packages/vitepress-plugin-og-image/src/vitepress/utils/svg/render.ts
* Added configuration for the result image width
* Added configuration for the max characters per line
=> feat(og image): more configurations

cspell.config.yaml, package.json, packages/vitepress-plugin-enhanced-readabilities/src/client/locales.ts, packages/vitepress-plugin-enhanced-readabilities/src/locales/index.ts, packages/vitepress-plugin-enhanced-readabilities/src/locales/ru-RU.yaml, packages/vitepress-plugin-git-changelog/src/client/locales.ts, packages/vitepress-plugin-git-changelog/src/locales/index.ts, packages/vitepress-plugin-git-changelog/src/locales/ru-RU.yaml, pnpm-lock.yaml
Hello. We'd like to help translate plugins and documentation into our team's native language, and it might be useful for other authors as well.
As a start and for evaluation - I and @X1Z53 have added builtin localizations for `git-changelog` and `enhanced-readabilities`.
If you have any feedback or see any issues - we'd love to hear from you.
=> feat(i18n): add Russian locales to `git-changelog` and `enhanced-readabilities`

docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/src/client/composables/changelog.ts, packages/vitepress-plugin-git-changelog/src/client/utils.ts
closes: #259
The format and scheme mentioned in #259 was not used because it conflicted with some of the ideas in #269.
=> feat(git-changelog): add authors for specific page

docs/.vitepress/config.ts, docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/build.config.ts, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitRegularLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/CommitTagLine.vue, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/client/composables/changelog.ts, packages/vitepress-plugin-git-changelog/src/client/utils.ts, packages/vitepress-plugin-git-changelog/src/vite/git.ts, packages/vitepress-plugin-git-changelog/src/vite/types.ts
=> fix(git-changelog): layout of commit inline authors and hmr bugs

packages/vitepress-plugin-git-changelog/src/client/composables/changelog.ts
=> fix(git-changelog): sort commits before truncating tags

docs/vite.config.ts, packages/vitepress-plugin-git-changelog/src/client/components/Contributors.vue, packages/vitepress-plugin-git-changelog/src/types/index.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
Our team took on a new project in which there was a need to localize contributor names for better internationalization.
I would like to propose my own implementation of this functionality.
In `Author` (`Contributor`) type inside `mapAuthors` option we create `i18n` field with the following structure:
```ts
i18n: {
'locale-code': 'name',
}
```
Example:
```ts
mapAuthors: [
{
name: "Anton Politov",
i18n: {
'ru-RU': 'Антон Политов',
},
...
}
]
```
Maybe it can be helpful for someone
=> feat(i18n - git-changelog): add locale support for contributors

docs/pages/en/integrations/vitepress-plugin-git-changelog/configure-ui.md, docs/pages/zh-CN/integrations/vitepress-plugin-git-changelog/configure-ui.md, packages/vitepress-plugin-git-changelog/src/client/components/Changelog.vue, packages/vitepress-plugin-git-changelog/src/client/types.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
Resolve profile pictures for GitHub emails in commit authors.
Resolves #277
Based on @nekomeowww's suggestions: https://github.com/nolebase/integrations/issues/277#issuecomment-2254111802
=> feat(git changelog): resolve profile picture for GitHub emails, new option to hide no data texts

docs/pages/en/integrations/vitepress-plugin-git-changelog/getting-started.md, packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
* Resolve GitHub profile URL based on a contributor's GitHub no-reply email
* Document how contributor information is resolved
=> feat(git changelog): resolve contributors' GitHub profile URL

packages/vitepress-plugin-git-changelog/src/vite/helpers.test.ts, packages/vitepress-plugin-git-changelog/src/vite/helpers.ts
may resolve: #231 (with the work done on #293 and #294)?
Just matching each email once (github no reply), the features introduced in #293 and #294 match each email address a total of 2 times.
=> pref: reduce the count of regular matches

packages/vitepress-plugin-inline-link-preview/src/client/components/InlineLinkPreview.vue
https://github.com/nolebase/integrations/issues/297
=> Update style of InlineLinkPreview.vue

docs/pages/en/integrations/vitepress-plugin-inline-link-preview/getting-started.md, docs/pages/zh-CN/integrations/vitepress-plugin-inline-link-preview/getting-started.md
https://github.com/nolebase/integrations/issues/308
=> docs(inline link preview): add vite config description for ssr

packages/markdown-it-bi-directional-links/src/index.ts, packages/markdown-it-bi-directional-links/src/utils.ts
- Obsidian allows matching files case-insensitively
- Omitting the link path links to the file itself, i.e. `[[#Foo]]` links to `#Foo` in the same file
=> fix(bi-directional-links): match case-insensitively, handle self-links

docs/pages/en/integrations/vitepress-plugin-enhanced-readabilities/index.md, docs/pages/zh-CN/integrations/vitepress-plugin-enhanced-readabilities/index.md
Updated Vite configuration to properly handle .vue files from @nolebase/ui. Fixed "Unknown file extension '.vue'" error during Vitepress build process.
Add the following line to the `optimizeDeps.exclude` / `ssr.noExternal` section in the Vite config:
`'@nolebase/ui'`.
The build error example:
```
build error:
Unknown file extension ".vue" for /vercel/path0/node_modules/@nolebase/ui/dist/components/NuTag/index.vue
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".vue" for /vercel/path0/node_modules/@nolebase/ui/dist/components/NuTag/index.vue
at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
at defaultLoad (node:internal/modules/esm/load:143:22)
at async …
```
=> docs: fix build issue in vite config

packages/vitepress-plugin-git-changelog/src/locales/ru-RU.yaml
Fix `titleid` format in ru locale in vitepress-plugin-git-changelog
=> Fix titleid format in ru locale in vitepress-plugin-git-changelog

docs/pages/en/index.md, docs/pages/en/ui/input-horizontal-radio-group/index.md, docs/pages/zh-CN/index.md, docs/pages/zh-CN/ui/input-horizontal-radio-group/index.md, packages/ui/src/components/NuInputHighlight.vue, packages/ui/src/components/NuInputSlider.vue, packages/ui/src/index.ts, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitch.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchContentLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/LayoutSwitchPageLayoutMaxWidthSlider.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/Spotlight.vue, packages/vitepress-plugin-enhanced-readabilities/src/client/components/SpotlightStyles.vue
=> fix(enhanced-readabilities): use plain CSS styles to prevent outline class overrides (#315)

docs/.vitepress/twoslashConfig.ts, docs/package.json, docs/pages/en/integrations/vitepress-plugin-breadcrumbs/index.md, docs/pages/zh-CN/integrations/vitepress-plugin-breadcrumbs/index.md, pnpm-lock.yaml
=> docs(breadcrumbs): fix twoslash error when build docs

packages/vitepress-plugin-breadcrumbs/src/client/components/NolebaseBreadcrumbs.vue
Old version of breadcrumbs does not wrap line correctly, this patch fixes this by just removing the flex.
Before:
After:
=> style: breadcrumbs now warps line correctly

docs/pages/zh-CN/integrations/markdown-it-unlazy-img/index.md
In the zh-CN version of the `markdown-it-unlazy-img` documentation, the package name in the installation command has not been updated. Using the incorrect package name (`markdown-it-bi-unlazy-img`) will result in a package not found error. 
The English documentation has the correct package name.
Update the package name in the installation command from `markdown-it-bi-unlazy-img` to `markdown-it-unlazy-img` in the zh-CN documentation.
- Corrected the package name in the installation command in the `zh-CN` documentation `markdown-it-unlazy-img` file.
=> docs(markdown-it-unlazy-img): correct installation command

packages/vitepress-plugin-index/src/vitepress/recentUpdates.ts
https://github.com/nolebase/nolebase/issues/143
The missing slash is recognized as a relative path and is now added when generating the data,
should this be added when rendering?
Additionally, in a Windows environment (Node.js v18.19.0), patterns using backslashes cannot resolve files. They need to be replaced with forward slashes.
=> fix(recentUpdates): path parsing error

docs/pages/en/integrations/markdown-it-bi-directional-links/getting-started.md, docs/pages/zh-CN/integrations/markdown-it-bi-directional-links/getting-started.md, packages/markdown-it-bi-directional-links/src/index.ts, packages/markdown-it-bi-directional-links/src/utils.ts
**增加选项**：noNoMatchedStillWork
**预期效果**：失效链接为偏红色的a标签
**网站实例1**：维基百科（wikipedia），点击失效链接会进入到创建该词条的新页面（功能不支持，只是模拟样式）
https://zh.wikipedia.org/wiki/%E6%95%B0%E5%AD%A6%E5%AD%A6%E7%A7%91%E5%88%86%E7%B1%BB%E6%A0%87%E5%87%86
**网站实例2**：（绿色的链接没有对应内容）
https://www.bananaspace.org/wiki/%E9%A6%99%E8%95%89%E7%A9%BA%E9%97%B4:%E5%86%99%E4%BD%9C%E8%AE%A1%E5%88%92
**软件实例**：Obsidian
这个默认在样式上似乎不区分链接是否有效，反正哪怕是没有对应页他也渲染成a标签。只是点击时不再跳转，而是自动创建该页面
**原来效果**：（稍微有些丑陋）
=> feat(bi-link): allow invalid link

packages/ui-asciinema/src/asciinema.d.ts, packages/ui-asciinema/src/components/NuAsciinemaPlayer.vue
- Fixes #400
ui-asciinema's `controls` can be `true`, `false`, or `'auto'`.
Before, the type did not allow `'auto'`.
With this PR, the type allows all possible values.
I modified both of these files manually. Not sure if the `d.ts` update was supposed to be done by some automated process — I ran the build `pnpm run packages:build` after changing only the Vue component file, and the `d.ts` didn't change.
=> fix(ui-asciinema): controls is boolean or 'auto' [#400]

docs/pages/en/ui/asciinema-player/index.md, docs/pages/zh-CN/ui/asciinema-player/index.md, packages/ui-asciinema/README.md
- VitePress convention is to configure Vite in the VitePress config file (ref: https://vitepress.dev/reference/site-config#vite). Updates the docs' code samples to follow that convention.
- Even after reading the linked Vite SSR docs, I didn't understand why the package needed to be made noExternal… until I tried building my VitePress site, and the build failed. Updates the ssr.noExternal docs to clarify that.
- Documents how to register a component globally
=> ui-asciinema docs: ssr.noExternal motivation, Markdown use, global registration

.github/workflows/ci-build.yaml, .github/workflows/ci.yaml, .github/workflows/production-docs-deployment.yaml, .github/workflows/release.yaml, package.json, packages/markdown-it-bi-directional-links/package.json, packages/markdown-it-element-transform/package.json, packages/markdown-it-unlazy-img/package.json, packages/ui-asciinema/package.json, packages/ui-rive-canvas/package.json, packages/ui/package.json, packages/vitepress-plugin-breadcrumbs/package.json, packages/vitepress-plugin-enhanced-mark/package.json, packages/vitepress-plugin-enhanced-readabilities/package.json, packages/vitepress-plugin-git-changelog/package.json, packages/vitepress-plugin-highlight-targeted-heading/package.json, packages/vitepress-plugin-index/package.json, packages/vitepress-plugin-inline-link-preview/package.json, packages/vitepress-plugin-meta/package.json, packages/vitepress-plugin-og-image/package.json, packages/vitepress-plugin-page-properties/package.json, packages/vitepress-plugin-sidebar/package.json, packages/vitepress-plugin-thumbnail-hash/package.json
- no need to set publish script for each package, `pnpm publish -r` is enough 
- sync github release in ci
- provide PROVENANCE
- use setup-node build-in cache
- run test in linux and windows (ci failed because #388, not this pr intro)
---
BTW, there is a lot of wasted resources in the current CI, such as.
- push: build packages 2 times
- pr: build packages 3 times
- release (with push): build packages 3 times
However, there seems to be no better solution at the moment.
=> ci: refactor workflows

packages/vitepress-plugin-enhanced-readabilities/src/client/types.ts
fix: types.ts 两处 `@default` 默认值错误
related issue: #455
=> fix: two `@default` typo in types.ts (#455)

.github/renovate.json
在组织级别管理 renovate 配置，以便统一更新。
此外，我们实无必要如此频繁的更新依赖项，这会打扰 watcher，我认为每周或每月是一个合适的选择。
目前的配置中，默认每月更新，在 intergrations 等有必要频繁更新的仓库中，我们覆盖更新计划为每周。
此外，对非 major 更新，如果能通过 build、test 等 ci，则自动合并。
你觉得怎么样？
=> chore: use org renovate config and override schedule to weekly
